blank_issues_enabled: false
contact_links:
  - name: 🙌 Feedback and support
    url: https://wtw.dev/chat
    about: 'This issue tracker is not for feature requests or support questions. Join us on Discord!'
